create table if not exists public.enterprises (
  id bigint generated by default as identity primary key,
  source_row integer not null,
  lg_st_code text,
  state text,
  lg_dt_code text,
  district text,
  pincode text,
  registration_date date,
  enterprise_name text,
  communication_address text,
  activities text,
  created_at timestamptz not null default now()
);

create table if not exists public.enterprise_import_rows (
  source_row integer not null,
  lg_st_code text,
  state text,
  lg_dt_code text,
  district text,
  pincode text,
  registration_date date,
  enterprise_name text,
  communication_address text,
  activities text
);

create unique index if not exists enterprises_source_row_key
  on public.enterprises (source_row);

create index if not exists enterprises_state_idx
  on public.enterprises (state);

create index if not exists enterprises_district_idx
  on public.enterprises (district);

create index if not exists enterprises_pincode_idx
  on public.enterprises (pincode);

create index if not exists enterprises_registration_date_idx
  on public.enterprises (registration_date);

create index if not exists enterprises_lg_st_code_idx
  on public.enterprises (lg_st_code);

create index if not exists enterprises_lg_dt_code_idx
  on public.enterprises (lg_dt_code);

create index if not exists enterprises_state_district_idx
  on public.enterprises (state, district);

create extension if not exists pg_trgm;

create index if not exists enterprises_enterprise_name_trgm_idx
  on public.enterprises using gin (enterprise_name gin_trgm_ops);

create index if not exists enterprises_address_trgm_idx
  on public.enterprises using gin (communication_address gin_trgm_ops);

create index if not exists enterprises_activities_trgm_idx
  on public.enterprises using gin (activities gin_trgm_ops);

create or replace function public.begin_enterprise_import()
returns void
language sql
security definer
set search_path = public
as $$
  truncate table public.enterprise_import_rows;
$$;

create or replace function public.complete_enterprise_import()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  imported_count bigint := 0;
  batch_count bigint;
  batch_size constant integer := 5000;
begin
  -- Large CSV imports can exceed the default Postgres statement timeout when we
  -- do a single truncate + insert from the staging table to the main table.
  set local statement_timeout = '10min';
  set local lock_timeout = '30s';

  -- Drop heavy indexes before the bulk load and recreate them after the final
  -- insert. This avoids paying the cost of index maintenance during the import.
  drop index if exists public.enterprises_source_row_key;
  drop index if exists public.enterprises_state_idx;
  drop index if exists public.enterprises_district_idx;
  drop index if exists public.enterprises_pincode_idx;
  drop index if exists public.enterprises_registration_date_idx;
  drop index if exists public.enterprises_lg_st_code_idx;
  drop index if exists public.enterprises_lg_dt_code_idx;
  drop index if exists public.enterprises_state_district_idx;
  drop index if exists public.enterprises_enterprise_name_trgm_idx;
  drop index if exists public.enterprises_address_trgm_idx;
  drop index if exists public.enterprises_activities_trgm_idx;

  truncate table public.enterprises restart identity;

  loop
    with batch as (
      select source_row,
             lg_st_code,
             state,
             lg_dt_code,
             district,
             pincode,
             registration_date,
             enterprise_name,
             communication_address,
             activities
      from public.enterprise_import_rows
      order by source_row
      limit batch_size
    )
    insert into public.enterprises (
      source_row,
      lg_st_code,
      state,
      lg_dt_code,
      district,
      pincode,
      registration_date,
      enterprise_name,
      communication_address,
      activities
    )
    select
      source_row,
      lg_st_code,
      state,
      lg_dt_code,
      district,
      pincode,
      registration_date,
      enterprise_name,
      communication_address,
      activities
    from batch;

    get diagnostics batch_count = row_count;
    exit when batch_count = 0;

    imported_count := imported_count + batch_count;

    delete from public.enterprise_import_rows
    where source_row in (
      select source_row
      from public.enterprise_import_rows
      order by source_row
      limit batch_size
    );
  end loop;

  create unique index if not exists enterprises_source_row_key
    on public.enterprises (source_row);
  create index if not exists enterprises_state_idx
    on public.enterprises (state);
  create index if not exists enterprises_district_idx
    on public.enterprises (district);
  create index if not exists enterprises_pincode_idx
    on public.enterprises (pincode);
  create index if not exists enterprises_registration_date_idx
    on public.enterprises (registration_date);
  create index if not exists enterprises_lg_st_code_idx
    on public.enterprises (lg_st_code);
  create index if not exists enterprises_lg_dt_code_idx
    on public.enterprises (lg_dt_code);
  create index if not exists enterprises_state_district_idx
    on public.enterprises (state, district);

  create index if not exists enterprises_enterprise_name_trgm_idx
    on public.enterprises using gin (enterprise_name gin_trgm_ops);
  create index if not exists enterprises_address_trgm_idx
    on public.enterprises using gin (communication_address gin_trgm_ops);
  create index if not exists enterprises_activities_trgm_idx
    on public.enterprises using gin (activities gin_trgm_ops);

  return imported_count;
end;
$$;

create or replace function public.enterprise_meta(selected_state text default null)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'total', (select count(*) from public.enterprises),
    'states', coalesce(
      (select jsonb_agg(state order by state)
       from (select distinct state from public.enterprises where state is not null) s),
      '[]'::jsonb
    ),
    'districts', coalesce(
      (select jsonb_agg(district order by district)
       from (
         select distinct district
         from public.enterprises
         where district is not null
           and (selected_state is null or state = selected_state)
         limit 500
       ) d),
      '[]'::jsonb
    )
  );
$$;
