create table if not exists public.enterprises (
  id bigint generated by default as identity primary key,
  source_row integer not null,
  lg_st_code text,
  state text,
  lg_dt_code text,
  district text,
  pincode text,
  registration_date date,
  enterprise_name text,
  communication_address text,
  activities text,
  created_at timestamptz not null default now()
);

create table if not exists public.enterprise_import_rows (
  source_row integer not null,
  lg_st_code text,
  state text,
  lg_dt_code text,
  district text,
  pincode text,
  registration_date date,
  enterprise_name text,
  communication_address text,
  activities text
);

create table if not exists public.enterprise_import_state (
  name text primary key,
  value text not null default 'idle'
);

create unique index if not exists enterprises_source_row_key
  on public.enterprises (source_row);

create index if not exists enterprises_state_idx
  on public.enterprises (state);

create index if not exists enterprises_district_idx
  on public.enterprises (district);

create index if not exists enterprises_pincode_idx
  on public.enterprises (pincode);

create index if not exists enterprises_registration_date_idx
  on public.enterprises (registration_date);

create index if not exists enterprises_lg_st_code_idx
  on public.enterprises (lg_st_code);

create index if not exists enterprises_lg_dt_code_idx
  on public.enterprises (lg_dt_code);

create index if not exists enterprises_state_district_idx
  on public.enterprises (state, district);

create extension if not exists pg_trgm;

create index if not exists enterprises_enterprise_name_trgm_idx
  on public.enterprises using gin (enterprise_name gin_trgm_ops);

create index if not exists enterprises_address_trgm_idx
  on public.enterprises using gin (communication_address gin_trgm_ops);

create index if not exists enterprises_activities_trgm_idx
  on public.enterprises using gin (activities gin_trgm_ops);

create or replace function public.begin_enterprise_import()
returns void
language sql
security definer
set search_path = public
as $$
  truncate table public.enterprises restart identity;
  truncate table public.enterprise_import_rows;
  insert into public.enterprise_import_state (name, value)
  values ('enterprise_import_active', 'true')
  on conflict (name) do update set value = 'true';
$$;

create or replace function public.complete_enterprise_import(batch_size integer default 5000)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  processed_count bigint := 0;
  current_batch_size integer := coalesce(batch_size, 5000);
  has_active_import boolean;
begin
  if current_batch_size <= 0 then
    current_batch_size := 1000;
  end if;

  set local statement_timeout = '30min';
  set local lock_timeout = '30s';

  select exists (
    select 1
    from public.enterprise_import_state
    where name = 'enterprise_import_active' and value = 'true'
  ) into has_active_import;

  if not has_active_import then
    truncate table public.enterprises restart identity;
    insert into public.enterprise_import_state (name, value)
    values ('enterprise_import_active', 'true')
    on conflict (name) do update set value = 'true';
  end if;

  with batch as (
    select source_row,
           lg_st_code,
           state,
           lg_dt_code,
           district,
           pincode,
           registration_date,
           enterprise_name,
           communication_address,
           activities
    from public.enterprise_import_rows
    order by source_row
    limit current_batch_size
  )
  insert into public.enterprises (
    source_row,
    lg_st_code,
    state,
    lg_dt_code,
    district,
    pincode,
    registration_date,
    enterprise_name,
    communication_address,
    activities
  )
  select
    source_row,
    lg_st_code,
    state,
    lg_dt_code,
    district,
    pincode,
    registration_date,
    enterprise_name,
    communication_address,
    activities
  from batch
  where source_row not in (select source_row from public.enterprises);

  get diagnostics processed_count = row_count;

  delete from public.enterprise_import_rows
  where source_row in (
    select source_row
    from public.enterprise_import_rows
    order by source_row
    limit current_batch_size
  );

  if (select count(*) from public.enterprise_import_rows) = 0 then
    create unique index if not exists enterprises_source_row_key
      on public.enterprises (source_row);
    create index if not exists enterprises_state_idx
      on public.enterprises (state);
    create index if not exists enterprises_district_idx
      on public.enterprises (district);
    create index if not exists enterprises_pincode_idx
      on public.enterprises (pincode);
    create index if not exists enterprises_registration_date_idx
      on public.enterprises (registration_date);
    create index if not exists enterprises_lg_st_code_idx
      on public.enterprises (lg_st_code);
    create index if not exists enterprises_lg_dt_code_idx
      on public.enterprises (lg_dt_code);
    create index if not exists enterprises_state_district_idx
      on public.enterprises (state, district);

    create index if not exists enterprises_enterprise_name_trgm_idx
      on public.enterprises using gin (enterprise_name gin_trgm_ops);
    create index if not exists enterprises_address_trgm_idx
      on public.enterprises using gin (communication_address gin_trgm_ops);
    create index if not exists enterprises_activities_trgm_idx
      on public.enterprises using gin (activities gin_trgm_ops);

    insert into public.enterprise_import_state (name, value)
    values ('enterprise_import_active', 'false')
    on conflict (name) do update set value = 'false';
  end if;

  return processed_count;
end;
$$;

create or replace function public.enterprise_meta(selected_state text default null)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'total', (select count(*) from public.enterprises),
    'states', coalesce(
      (select jsonb_agg(state order by state)
       from (select distinct state from public.enterprises where state is not null) s),
      '[]'::jsonb
    ),
    'districts', coalesce(
      (select jsonb_agg(district order by district)
       from (
         select distinct district
         from public.enterprises
         where district is not null
           and (selected_state is null or state = selected_state)
         limit 500
       ) d),
      '[]'::jsonb
    )
  );
$$;
